services:
#  https-portal:
#    image: steveltn/https-portal:1
#    ports:
#      - "80:80"
#      - "443:443"
#    links:
#      - face
#    restart: always
#    environment:
#      DOMAINS: 'app.mega-fiscal.com -> http://face:8082'

  redis:
    image: redis:4
    ports:
      - 6379:6379
  face:
    build:
      context: .
      dockerfile: ./fiscal_face/Dockerfile
    ports:
      - 8082:8082
  revise:
    build:
      context: .
      dockerfile: ./revise_service/Dockerfile
    ports:
      - 8085:8085
#  fink:
#    build:
#      context: .
#      dockerfile: ./fink_service/Dockerfile
#    ports:
#      - 8086:8086




